version: "3" # You should specify the version of Docker Compose you are using

services:
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    image: ghcr.io/alirezaalizade025/jora/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000"
    environment:
      - DB_HOST=db
      - DB_USER=jora
      - DB_PASSWORD=LhTapIg4ZGG03iWjSz9OSsd6g
      - DB_NAME=jora_db
      - DB_SSLMODE=disable
      - SERVE_MODE=naturel
    volumes:
      - ./certificates/private.pem:/app/private.pem
      - ./certificates/public.pem:/app/public.pem
    depends_on:
      - db

  api:
    image: ghcr.io/alirezaalizade025/jora:latest
    container_name: api
    restart: always
    ports:
      - "8181"
    environment:
      - DB_HOST=db
      - DB_USER=jora
      - DB_PASSWORD=LhTapIg4ZGG03iWjSz9OSsd6g
      - DB_NAME=jora_db
      - DB_SSLMODE=disable
      - SERVE_MODE=naturel
    volumes:
      - ./certificates/private.pem:/app/private.pem
      - ./certificates/public.pem:/app/public.pem
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jora
      - POSTGRES_PASSWORD=LhTapIg4ZGG03iWjSz9OSsd6g
      - POSTGRES_DB=jora_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
