name: Build Frontend

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'


    - name: Install Dependencies
      run: yarn install
      working-directory: frontend/ 
      
    - name: build front
      run: yarn build
      working-directory: frontend/ 

    - name: 'Create env file'
      run: |
        touch .env.production
        echo NEXT_PUBLIC_API_BASE_URL=${{ env.NEXT_PUBLIC_API_BASE_URL }} >> .env
        cat .env.production

    - name: Build and push frontend Docker image
      run: |
        docker build --file frontend/config/Dockerfile -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/frontend:latest frontend/
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/frontend:latest
      env:
        DOCKER_BUILDKIT: 1