name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build Go app
      run: go build -v
      working-directory: backend/  # Set the working directory to /backend

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest backend/
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
      env:
        DOCKER_BUILDKIT: 1


    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          # Pull the latest Docker image from the container registry on the server
          docker pull ghcr.io/your-username/your-repo:latest
          # Stop the existing containers (if any)
          docker-compose -f /path/to/docker-compose.yml down
          # Start the updated containers with the new image
          docker-compose -f /path/to/docker-compose.yml up -d

          