# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build Go app
      run: go build -o jora ./...

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/jora:latest .
        docker push docker.pkg.github.com/${{ github.repository }}/jora:latest

    - name: Cleanup
      run: docker logout docker.pkg.github.com